title: Samuel Fiyinfoluwa Adekunle # Add your name
role: Frontend Engineer # Add your role/position
company: Tizela # Add your company name

description: >- # this means to ignore newlines until "baseurl:"
  A self-taught Fullstack Web Engineer. Currently shaping user experiences on the web.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://links.fiyin.ng" # the base hostname & protocol for your site, e.g. http://example.com
keywords: Samuel Adekunle, Frontend Engineer, Tizela, self-taught, web engineer, user experiences, Nigerian, developer, UI/UX, developer, fullstack
theme-color: "#4ade80" # Used for browser theme-color meta tag

gravatar: 8144e6d8a310aa504e7f7e369a53c562 # Gravatar md5 hash
image: /assets/avatar.jpeg # Add your avatar image src here
branding: false # Your name will be replaced with your logo if set to true, change your logo here "_includes/svg/logo.svg"

### Author Info ###
author:
  name: Samuel Adekunle
  x: try_samuell
  instagram: y_samuelll
  github: try-samuel
  linkedin: samuel-adekunle-a995a8213
  # figma             : vyshnav
  # buy me a coffee   : vyshnav
  # layers            : vyshnav
#  dribbble          : vyshnav_
#  youtube           : vyshnav
#  facebook          : vyshnav
#  twitch            : vyshnav
#  gitlab            : vyshnav
#  codepen           : vyshnav

### Analytics ###
analytics:
  enabled: false
  google:
    tracking_id: #Add your Google analytics tracking ID here

sass:
  style: compressed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor
